server:
  port: 7002

spring:
  application:
    name: eureka-server-7001

eureka:
  instance:
    hostname: eureka7002.scs.com
  client:
    serviceUrl:
      defaultZone: http://eureka7001.scs.com:7001/eureka/