server:
  port: 7001

eureka:
  instance: # eureka 服务器端的实例名称
    hostname: eureka-localhost
  client: # 是否向注册中心注册自己
    registerWithEureka: false
    # false 表示自己就是注册中心，我的职责就是维护服务实例，并不需要检索服务
    fetchRegistry: false
    # 设置与 eureka server 交互的地址，查询服务和注册服务读需要依赖这个地址
    serviceUrl: http://${eureka.instance.hostname}:${server.port}/eureka/
