server:
  port: 9527

logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: trace
    org.springframework.web.reactive: trace
    org.springframework.boot.autoconfigure.web: trace

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
