server:
  port: 9527

logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: trace
    org.springframework.web.reactive: trace
    org.springframework.boot.autoconfigure.web: trace

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # path
        - id: route_001
          uri: lb://server-over-consul
          predicates:
            - Path=/server/**

        # after
        - id: route_002
          uri: lb://server-over-consul
          predicates:
            - Path=/echo/**
            - After=2099-09-07T22:33:30.000+08:00[Asia/Shanghai]

        # before
        - id: route_003
          uri: lb://server-over-consul
          predicates:
            - Path=/echo/**
            - Before=2000-09-07T22:33:30.000+08:00[Asia/Shanghai]
