server:
  port: 9527

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment01
          uri: http://localhost:8001
          predicates:
            - Path=/provider/echo/**